apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: api-conversao
  template:    
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: rossalli/api-conversao
          ports:
            - containerPort: 80
